version: "3.7"
services:
  app:
    container_name: datawow_test_client
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next